### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by zer0x64**
Initial commit for the WASM bindings. To build, use `wasm-pack build`

### CODE REVIEW

**Comment by zer0x64** [comment]
Note: This will also require some changes to the CI and the dev-dependencies to run real WASM tests(using `wasm-pack test`)

**Comment by c0dearm** [comment]
Thanks for the PR! Yup, I am aware, there are no GitHub actions for `wasm-pack`, so I will have to manually specify the commands for build and test.

I will do it tomorrow, along with nice error handling. Before merging, I would like to have the following features, if possible:

- [x] API closer to the main `sharks` crate (i.e. JavaScript object with methods, instead of isolated functions)
- [x] Error handling
- [x] Add some tests and docs
- [x] Proper CI

**Comment by c0dearm** [comment]
I have fixed the CI, done some error handling and improved the API, also written tests and updated usage docs. Now it is almost the same way of working as the original crate, you have a `SharksJS` object with the methods to generate shares and recover a secret.

I haven't been able to return an `Iterator` from the `dealer` method to make obtaining shares more flexible, you need to specify the number of shares beforehand. Not sure it is actually possible to return an Iterator with wasm.

Let me know if you are okay with this or if I am missing something before merging!

**Comment by zer0x64** [comment]
Hey! That looks awesome! However, my test project is not on my current PC, have you tried actually calling it from a javascript project? If you did and everything works, it's okay to merge, if not I can test that later!

**Comment by c0dearm** [comment]
I did! The usage example in the `README` file is exactly the test I did (except for the require path) 👍

**Review by c0dearm — APPROVED** [review]

**Pull request merged**
